apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: my-app
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: my-app
  type: LoadBalancer

